import react from '@vitejs/plugin-react'
import { defineConfig } from 'vite'

export default defineConfig({
  plugins: [react()],
  build: {
    target: 'esnext',
  },
  server: {
    port: 5173,
  },
  // Exclude axen-form from dep optimization so that the CSS injection IIFEs
  // generated by vite-plugin-css-injected-by-js are NOT stripped by esbuild.
  optimizeDeps: {
    exclude: ['@axenstudio/axen-form'],
  },
})
